### ISSUE TITLE
2gb filesize limit in download?

### ISSUE THREAD

**Issue by keef2k5** [brainfoolong/web-ftp-client#10]
Hi,

I have successfully installed this great ftp client and started using it. But I found the maximum file-size of the downloaded file is exactly 2GB. Any file that is larger than 2gb download failed. Have You any solution to breakthrough this limit?

I used latest released version from github: 
v0.12.0 alpha4
linux is a debian wheezy x86.
node --version v9.8.0
npm --version 5.6.0

thanks,
KeeF

**Comment by brainfoolong** [comment]
Hi,

do you have this issues with FTP or SFTP?

**Comment by keef2k5** [comment]
oh, sorry i forgot this: i used ftp.

**Comment by brainfoolong** [comment]
Ok, are there any errors? In the logs, in the interface, in your syslog?

**Comment by keef2k5** [comment]
nope, i not find any log-entries related to wfc, nor good or bad, also error.log and output.log are empty. i  running the wfc as root (later i will change this to a specified user). i just see the error on the interface nothing elsewhere and ofcourse i see the file-size is less than the original file on the ftp.
Can I run wfc in 'debug mode' or verbose to get more information related to this error?

**Comment by brainfoolong** [comment]
Can you post the exact error message?
Also, have you maybe the chance to this against a SFTP server, this may help to find out if it's system based or application based problem.

FYI: I use SFTP on a daily basis with single files over 10GB on a synology system, this work without flaws. But i never used FTP with such big files. Maybe it's a limitation in the underlaying FTP library that i use.

**Comment by keef2k5** [comment]
i tried with sftp, but results are the same: transfer stopped at 2gb with shows file on error-list, but none any errors in the log files. i can transfer large files with 'yafc' ftp client and sftp from cli also can transfer larger than 2gb files.
maybe this is the 32bit linux and/or nodejs limitation?

**Comment by brainfoolong** [comment]
This is probably the case, the 32bit limitation. As it seems as it is a system based problem, not a specific protocol problem. Unfortunetely i cannot help you more here.
