### ISSUE TITLE
i have a question about download retry

### ISSUE THREAD

**Issue by hayden-han** [brainfoolong/web-ftp-client#11]
hi! I'm curious to use it.
When downloading a file from another ftp server, if the download is interrupted, is there a way to download the old local file again? where and how I change a code?

**Comment by brainfoolong** [comment]
Just re-download it but make sure you have enabled `Replace always` or `Replace when newer or size is different`.

**Comment by hayden-han** [comment]
@brainfoolong I found that way. But I don't want to replace existed file because file size is so big. is there a no way to resume with exist file??

**Comment by brainfoolong** [comment]
Unfortunetely no. The underlaying FTP and SFTP libraries don't support that.

**Comment by hayden-han** [comment]
@brainfoolong ok, thanks for helping me. one more thing, An output.log in logs folder is not written anything when I run this client by './wfc start'. how to see console.log()??

**Comment by brainfoolong** [comment]
Hm. It should because stdout will be written to output.log, stderr will be written to error.log.
You can test it native by running directly `node src/main.js start`, this will do the same as `./wfc start`
