### ISSUE TITLE
docker container ? 

### ISSUE THREAD

**Issue by silkyclouds** [brainfoolong/web-ftp-client#12]
Hey there! 

I was searching for a web ui sftp client and found your project! it seems very handy! 
would you consider to make a docker container so I can run it aside all my other dockers ? would be great ! 

thanks !

**Comment by brainfoolong** [comment]
Hi, i cannot do this because i have no idea of docker. I never used it.

**Comment by silkyclouds** [comment]
Ah well then it will be installed regularly I assume ;)

May I ask you why I’m getting this error ? 

root@Cream:~/brainfool# ./wfc start
Starting Web FTP Client...
Web FTP Client could not start


root@Cream:~/brainfool# ./wfc status
No server running (/home/plexuser/brainfool/wfc.pid is missing)

I create an empty wfc.pid to see if it helped but it actually didn’t.

here is what I do see in the error.log file :

root@Cream:~/brainfool/logs# cat error.log
./wfc: 42: ./wfc: node: not found

Thanks !!!

**Comment by brainfoolong** [comment]
Seems like `node` is not installed on your device. Maybe `nodejs` is? Test it with `nodejs -v`, if you get back a version number than you can use this to fix this.

Linux: If you've installed it and node as not available but nodejs is, than create a symlink with

    sudo ln -s `which nodejs` /usr/bin/node

**Comment by silkyclouds** [comment]
it indeed helped! It’s working great now ! 

Thanks !
