### ISSUE TITLE
Socket getrennt. Neuer Versuch in 5 Sekunden...

### ISSUE THREAD

**Issue by STX2k** [brainfoolong/web-ftp-client#13]
Moin, 

Ich wollte deinen FTP Client einmal testen. Hab es auch soweit zum laufen bekommen. Musste dafür aber noch das `nodejs-legacy` Paket installieren. Wenn ich jetzt das Webinterface aufrufe bekomme ich aber nur ein Ladebalken und dann sofort "Socket getrennt. Neuer Versuch in 5 Sekunden..." 

Der Error-Log ist leer. Die anderen ebenfalls. 

Hast du vielleicht einen Tipp?

Gruß STX

**Comment by brainfoolong** [comment]
Nodejs legacy dürfte zu alt sein. Installiere das normale `nodejs` Paket wenn möglich. Falls du dann das Problem hast das das Programm `node` nicht zur Verfügung steht, dann versuche die "Troubleshooting" Tipps -> https://github.com/brainfoolong/web-ftp-client#troubleshooting

**Comment by STX2k** [comment]
Danke für deine schnelle Antwort. Hab jetzt nodeJS neuinstalliert ` nodejs -v v8.11.3` und auch die Troubleshooting Tipps angewandt. 

`sudo ln -s `which nodejs` /usr/bin/node
ln: failed to create symbolic link '/usr/bin/node': File exists`

Sieht also eigentlich alles ganz gut aus. Dennoch bekomme ich immer noch den gleichen Fehler. :(

**Comment by brainfoolong** [comment]
Ok. Auf welchem OS hast du das installiert? Hast du, wenn du die Seite aufmachst und via F12 Entwicklerkonsole nachsiehst, irgendwelche Fehler im Tab "Console" oder "Netzwerk"?

**Comment by STX2k** [comment]
Ubuntu 16.04 LTS

Im Console Tab erhalte ich folgenden Fehler:
```
socket.js:10 WebSocket connection to 'ws://127.0.0.1:4341/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
cb @ socket.js:10
(anonymous) @ socket.js:21
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
A @ jquery-3.2.1.min.js:4
(anonymous) @ jquery-3.2.1.min.js:4
socket.js:15 WebSocket Error [object Event]
con.onerror @ socket.js:15
error (async)
cb @ socket.js:15
(anonymous) @ socket.js:21
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
A @ jquery-3.2.1.min.js:4
(anonymous) @ jquery-3.2.1.min.js:4
load (async)
send @ jquery-3.2.1.min.js:4
ajax @ jquery-3.2.1.min.js:4
r.(anonymous function) @ jquery-3.2.1.min.js:4
gl.socket.connect @ socket.js:21
(anonymous) @ global.js:66
j @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
fire @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
ready @ jquery-3.2.1.min.js:2
S @ jquery-3.2.1.min.js:3
(anonymous) @ VM10734:2
e.string.g.function.c.(anonymous function) @ VM10823:52
(anonymous) @ VM10734:2
b @ VM10734:1
(anonymous) @ VM10734:2
ja @ VM10823:53
l @ VM10823:50
```

Network spuckt nicht direkt einen Fehler aus. Lediglich einen 304 Not Modified auf die Angeforderten Ressourcen. 

Ich hab nochmal 2 Screenshots gemacht. 

https://i.imgur.com/KGTgeNc.png
https://i.imgur.com/lX4P6C1.png

**Comment by brainfoolong** [comment]
Ok, ich sehe hier immer wieder 127.0.0.1, die default config ist aber meist auf "localhost" eingestellt. Auch wenn es im Prinzip das selbe ist, probier mal "localhost" statt 127.0.0.1.

**Comment by STX2k** [comment]
Okay hab jetzt beides in der config.js ausprobiert, vorher hatte ich `null` drin stehen und hatte es dann mal geändert. Kommt dann aber auch nur wieder Errors. 

```
/opt/webftp/web-ftp-client/src/config.js:11
  'host': 127.0.0.1,
               ^^

SyntaxError: Unexpected number
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/webftp/web-ftp-client/src/routes.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/webftp/web-ftp-client/src/main.js:17:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

```
/opt/webftp/web-ftp-client/src/config.js:11
  'host': localhost,
          ^

ReferenceError: localhost is not defined
    at Object.<anonymous> (/opt/webftp/web-ftp-client/src/config.js:11:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/webftp/web-ftp-client/src/routes.js:6:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/webftp/web-ftp-client/src/main.js:17:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by brainfoolong** [comment]
Du hast einen Config Fehler. Die Werte müssen in Hochkomma stehen.

Also

    'host': 'localhost',

oder

    'host': '127.0.0.1',

**Comment by STX2k** [comment]
Okay hab jetzt beides ausprobiert. Fehler bleibt bestehen :(

**Comment by brainfoolong** [comment]
Ok, dann versuch ich es nochmal :) Bitte probier/mach folgendes

1. Poste hier deine `config.js`, wenn du 'localhost' drinstehen hast.
2. Du hast das auf Ubuntu installiert, wie bzw. mit welchem Browser rufst du die Seite dann auf?
3. Hast du die Installation in irgendeiner Sandbox / irgendeinem Container laufen?
4. Statt dem Startcommando `wfc start` probiere bitte mal `node src/main.js start` im Root Verzeichnis vom web-ftp-client und poste dann hier deine Fehler bzw. Meldungen die erscheinen.

**Comment by STX2k** [comment]
Danke für deine Geduld. 

```
'use strict'

const path = require('path')
const fs = require('fs')

/**
 * Default configuration
 * Override with local config.js file in root
 */
let config = {
  'host': 'localhost',
  'port': 4340,
  'development': false
}

// load config.js if exist
if (fs.existsSync(path.join(__dirname, '../config.js'))) {
  config = require(path.join(__dirname, '../config.js'))
}

module.exports = config

``` 

2. Chrome Version 67.0.3396.99 (Offizieller Build) (64-Bit) | Auch mit Edge und IE Probiert
3. Kein Container keine Sandbox
4. Bekomme auch keine Fehler angezeigt. 

` node v8.11.3`

**Comment by brainfoolong** [comment]
Ok.

1. Lass deine `config.js` unbearbeitet, d.h. nimm die originale vom Repository.
2. Beende alle aktuell laufenden WFC Instanzen (falls noch welche laufen) bzw. Starte mal neu
3. Start WFC dann wie beschrieben in der Github Readme
4. Kommt noch immer der selbe Fehler mit "Socket getrennt?"? Welche URL rufst du jetzt genau auf im Chrome? Rufst du das auch von dem Gerät auf auf dem du das installiert hast? Die URL sollte http://localhost:4340 sein wenn du das am selben Gerät aufrufst.

**Comment by STX2k** [comment]
Sorry für die späte Rückmeldung. Ich greife per SSH Tunnel und Portfowarding auf den WebFTP, da kein PW schutz davor ist wollte ich es nicht im Netzt erreichbar sein lassen. Ich hab beide URLs ausprobiert also IP und localhost. Problem bleibt bestehen.

**Comment by brainfoolong** [comment]
Ok. Bitte auch Port 4341 freigeben/forwarden. Dieser wird vom Websocket
benötigt. Also 4340 + 4341.

STX <notifications@github.com> schrieb am Mi., 18. Juli 2018, 14:31:

**Comment by STX2k** [comment]
Perfekt! Jetzt läuft es. Zwar nicht mit allen FTP Servern aber immerhin. Liegt aber wohl am fehlenden PRET Command Unterstützung und Passive Ports? Leider zeigts auch keine Errors nur Timeout oder Error. https://github.com/cmstest/node-ftp-pret 

Vielen Dank auf jeden fall für deine Hilfe!

PS: kann man dir auch per BTC spenden?

**Comment by brainfoolong** [comment]
Passive Support sollte möglich sein, muss aber gestehen ich nutze FTP selbst nicht, ich mach alles per SFTP. Ich nutze dieses Libary im Hintergrund -> https://github.com/mscdex/node-ftp - Das sollte PassivModi unterstützen.

BTC? Ja ich hab eine Adresse -> 34iAofHCr9Pah5WUMoVGQXAVbmVh2FuTRK

**Comment by STX2k** [comment]
Ah okay. Sieht so aus als kann er das auch nicht. 

`You need to use a client supporting PRET (PRE Transfer) to use PASV`

Schade aber danke trotzdem. Vielleicht für eine Zukünftige Version ;) - Spende kommt die Tage. Vielen Dank nochmal.

**Comment by brainfoolong** [comment]
Schade. Thx im vorraus :)
