### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by blackstormlab** [brainfoolong/web-ftp-client#14]
I'm greeted with a blank page on ip:4340

**Comment by brainfoolong** [comment]
Please provide more information

* OS
* Any errors on startup
* Any errors on command line
* F12 console log from your browser

**Comment by blackstormlab** [comment]
os =win10/win server 2016 datacenter
erros where do i find the errors ?

browser console log =

Refused to apply style from 'http://192.168.1.80:4340/stylesheets/dist/general.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
global.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
storage.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
lang.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
lang.values.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
socket.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
tpl.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
form.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
splitbox.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
global.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
8Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
storage.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
lang.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
lang.values.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
socket.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
tpl.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
form.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
splitbox.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):29 Uncaught ReferenceError: gl is not defined
    at (index):29
(index):1 Refused to apply style from 'http://192.168.1.80:4340/stylesheets/dist/general.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by blackstormlab** [comment]
oh btw thanks for the fast response

**Comment by brainfoolong** [comment]
It seems that it is not installed or running properly because no URL is able to be loaded by your browser. How you start the client and whats your command line messages that you see?

**Comment by blackstormlab** [comment]
![capture1](https://user-images.githubusercontent.com/35038928/44874442-7a814280-ac9b-11e8-8d79-d147c2c9dc0a.PNG)
this is what i get when i launch the bat

**Comment by blackstormlab** [comment]
further i dont see anything from the console

**Comment by brainfoolong** [comment]
On windows please use following guide
https://github.com/brainfoolong/web-ftp-client#install-windows

Just start the thing with opening the `wfc.bat` file in the main folder.

**Comment by brainfoolong** [comment]
Oh well, i see you have used this.
Do you have any logs in the `logs` folder?

**Comment by blackstormlab** [comment]
only a .gitignore file so no

**Comment by blackstormlab** [comment]
and yes i did follow the windows install

**Comment by brainfoolong** [comment]
Ok. Are you running this on the same machine as your opening it with your browser with?
Have you tried `http://localhost:4340` when this is true?

What's the output from `node -v`?

**Comment by blackstormlab** [comment]
same issue on localhost and where do i find this output ?

**Comment by blackstormlab** [comment]
sorry for wasting your time

**Comment by brainfoolong** [comment]
Nevermind about the output. Hmm... Seems to be a network issue on your machine. Maybe your firewall is blocking nodejs?

**Comment by blackstormlab** [comment]
firewall is disabled

**Comment by blackstormlab** [comment]
but on localhost that wouldnt matter does it

**Comment by brainfoolong** [comment]
It could be possible that your windows firewall does block this thing, even if it's local. But i also don't think that this is the problem here.

I try it out myself tomorrow with a fresh install on win10. Maybe it as a bug with win10.

**Comment by blackstormlab** [comment]
ok thanks see you then

**Comment by brainfoolong** [comment]
Ok i have done the following test and all works fine on my side.
- Download https://github.com/brainfoolong/web-ftp-client/releases/download/0.12.0/release-0.12.0.zip and unpack into a folder
- Run `npm install --production` in the folder where i've unpacked the zip in
- Run `wfc.bat`
- Goto browser `http://localhost:4340`
- Welcome screen is showing up

**Comment by blackstormlab** [comment]
thanks this time it worked even tho I did the exact same thing
also is it possible to change the port?

**Comment by brainfoolong** [comment]
The port can be changed via `config.js`. Copy `config.template.js` to `config.js` and modify it.

**Comment by testeur70** [comment]
Hello,

I just installed this app on my DS3615xs, I followed your installation guide  : 
- Installed nodejs 4
- Downloaded the zip and extract it in /volume1/web/web-ftp/
- Run 'npm install --production' (all was ok, no error returned)
- Applied the Automatic boot on startup for DSM 6 command
-browse to 192.168.1.53:4340 but only a blank page !
The server seems to work but impossible to display the correct ftp page !
I have no error message and the folder /logs/ contained 2 error files which are empty : error.log and output.log
Can you help me?
Thanks

Screenshot of my page :
(I have tryed different browser)
<a href="https://servimg.com/view/19332506/35"  target="_blank" ><img src="https://i25.servimg.com/u/f25/19/33/25/06/th/captur10.png" border="0" alt="Image hébergée par servimg.com" /></a>

**Comment by brainfoolong** [comment]
@testeur70 Please lets continue the issue here -> https://github.com/brainfoolong/web-ftp-client/issues/17

**Comment by brainfoolong** [comment]
I think i know the error here. The problem is probably that you have downloaded the repository master zip file, that's wrong. You have to download the latest release zip here: https://github.com/brainfoolong/web-ftp-client/releases
