### ISSUE TITLE
Blank Page on DS3615xs

### ISSUE THREAD

**Issue by brainfoolong** [brainfoolong/web-ftp-client#17]
I just installed this app on my DS3615xs, I followed your installation guide  : 
- Installed nodejs 4
- Downloaded the zip and extract it in /volume1/web/web-ftp/
- Run 'npm install --production' (all was ok, no error returned)
- Applied the Automatic boot on startup for DSM 6 command
-browse to 192.168.1.53:4340 but only a blank page !
The server seems to work but impossible to display the correct ftp page !
I have no error message and the folder /logs/ contained 2 error files which are empty : error.log and output.log
Can you help me?
Thanks

Screenshot of my page :
(I have tryed different browser)
<a href="https://servimg.com/view/19332506/35"  target="_blank" ><img src="https://i25.servimg.com/u/f25/19/33/25/06/th/captur10.png" border="0" alt="Image hébergée par servimg.com" /></a>

_Originally posted by @testeur70 in https://github.com/brainfoolong/web-ftp-client/issues/14#issuecomment-434599926_

**Comment by brainfoolong** [comment]
Can you please make a screenshot of your F12 error console from your browser while you loaded the page? Please make 2 screenshots, one of the "console" tab, one of the "network" tab.

**Comment by testeur70** [comment]
Hello,
Thank you for your fast answer ! 
You will find on the following link two screenshots : the console and the network tab. 

https://i25.servimg.com/u/f25/19/33/25/06/consol10.png

https://i25.servimg.com/u/f25/19/33/25/06/networ10.png

Thanks

**Comment by brainfoolong** [comment]
I think i know the error here. The problem is probably that you have downloaded the repository master zip file, that's wrong. You have to download the latest release zip here: https://github.com/brainfoolong/web-ftp-client/releases

**Comment by testeur70** [comment]
Yes, I 've cloned the Git release and downloaded the zip ! I will try to install the last alpha4 release.
How can I cleanly uinstall the previous release frm my DSM ?

**Comment by testeur70** [comment]
Thank you for your help. I installed the right package and all is OK now... Very great job this app works great and I think a lot of people using a Synology NAS, should know that this sof exist... Thanks again

**Comment by brainfoolong** [comment]
Great, thanks for the feedback.
