### ISSUE TITLE
Add a way to rely on FTP server auth

### ISSUE THREAD

**Issue by DrLecter** [brainfoolong/web-ftp-client#19]
Hi. I've started looking at your project as a web replacement for Filezilla. Our organization maintains an FTP server with his own MySQL driven user base. So it would be desirable to avoid an extra layer of authentication and rely purely on the FTP server permissions definition.

**Comment by brainfoolong** [comment]
Thx for the idea. Well. Using any other auth than the built in way is complicated. There is a fundamental change that is required to make this working. Such as: Disable built-in auth and let the user enter credentials from ftp everytime you want to connect to a certain ftp. Or other way: Disable built-in auth and define a specific FTP server to handle just the login mechanism in the background.
This app was not designed to work such way.
