### ISSUE TITLE
Synology installation

### ISSUE THREAD

**Issue by Kaelber** [brainfoolong/web-ftp-client#2]
Ich habe nun mal Deine neuste Version 0.12 auf meiner DS415+ mit DSM 5.2 installiert auf der das Paket node.js laeuft. Im Verzeichnis "web" habe ich das Verzeichnis "webftpclient" angelegt. Wenn ich jedoch

http://serverip/webftpclient

eingebe, erscheint nichts. Da die Doku etwas schlank ausfaellt, ist die Frage, was ist nun nicht richtig an der Installation?

**Comment by brainfoolong** [comment]
English only please.
After node works, do that steps for "Linux" as described in the synology installation.
`Via SSH terminal do the same as install linux. You can for sure use a shared folder.`

https://github.com/brainfoolong/web-ftp-client#install-linux

**Comment by Kaelber** [comment]
What it means or are the steps with

"Via SSH terminal do the same as install linux."

**Comment by brainfoolong** [comment]
You need to open a SSH Terminal (Command Line) to the synology, than you have to do the steps described in the readme.

https://www.wijngaard.org/using-putty-on-your-diskstation/
http://www.synology-wiki.de/index.php/Die_Kommandozeile

**Comment by Kaelber** [comment]
Okay, thats clear. To have entrance as root, is for me no problem on DSM 5.2 or DSM 6. My above steps doesnt works. Is possible to have a step by step instruction to install the software on a DS ?

**Comment by brainfoolong** [comment]
Actually, this is already a step by step instruction. There are no more steps inbetween.

https://github.com/brainfoolong/web-ftp-client#install-linux (Install linux and Install Synology)

I don't give instructions for how to use SSH on your NAS, that's not the point of this software. For this you can search other tutorials.

**Comment by christianromeni** [comment]
"unpack to a directory" does it matter wich directory? could you recommend one?

**Comment by brainfoolong** [comment]
It doesn't matter. It works everywhere. Maybe somewhere where nobody can access the directory via file sharing because some credentials will be saved to disk. But it depends on your device.

**Comment by Kaelber** [comment]
Up to now, running on a Synology DSx12+ or DSx15 with DSM 6.1.1 was not possible. It would be good to have a instruction for that.

**Comment by brainfoolong** [comment]
It was not possible because of what?

**Comment by Kaelber** [comment]
After installation in the "web" folder and the folder is named as "/volume1/web/web-ftp-client-master" I want to run "http://serverip/web-ftp-client-master/" I got a 403 as response.

**Comment by brainfoolong** [comment]
As the installation readme shows, you have to open it up with just http://IPTOSERVER:4340

**Comment by Kaelber** [comment]
Also that I have done, but I got a page error. I have to say to the server to use the port no. How I doe that?

**Comment by brainfoolong** [comment]
The server, if not configured different, using the port 4340 per default. So, nothing needed to configure here. Just install as described in `Install Linux` and `Install Synology` here https://github.com/brainfoolong/web-ftp-client#install-linux.

We turn in circles here...

**Comment by Kaelber** [comment]
What is content of "web-ftp-client.sh"? Doe you have a sample file?

**Comment by brainfoolong** [comment]
It will be a symbolic link to the file `yourapproot/wfc` when you use this command `sudo ln -s $(pwd)/wfc /usr/local/etc/rc.d/web-ftp-client.sh && sudo chmod 0755 wfc`

But this is just for auto boot on startup of synology.

**Comment by Kaelber** [comment]
I try

sudo ln -s /volume1/web/web-ftp-client-master/wfc /usr/local/etc/rc.d/web-ftp-client.sh && sudo chmod 0755 wfc

but after restart the DS it doesnt run.

**Comment by brainfoolong** [comment]
I close this.
