### ISSUE TITLE
Please provide an Arch Linux ARM package

### ISSUE THREAD

**Issue by SpaceAgeHero** [brainfoolong/web-ftp-client#20]
Dear dev,

please provide an Arch Linux ARM package:
https://archlinuxarm.org/wiki/Developers

Thanks! :-)

**Comment by brainfoolong** [comment]
Since this is a NodeJS script there is no need to special compile it for a platform.

**Comment by SpaceAgeHero** [comment]
But it would be easier to access and update by users, wouldn't it?
I'm aware that it would mean more effort for you though ... Especially if everyone begins to want a package for their distributions ...

**Comment by brainfoolong** [comment]
I honestly don't want to bother with any packaging for any distro :) Even if it is just docker.
