### ISSUE TITLE
Un-translated button "SPEICHERN"

### ISSUE THREAD

**Issue by GramThanos** [brainfoolong/web-ftp-client#3]
The buttons on the

- "Add new server" panel
- "Settings" panel
- "Usermaneger" panel

are not translated to "SAVE" (it is in german "SPEICHERN").

**Comment by brainfoolong** [comment]
Ok, thanks. I'll fix that in the next update.

**Comment by brainfoolong** [comment]
Finally :) Thx @DrLecter
