### ISSUE TITLE
Can you help me to install please ?

### ISSUE THREAD

**Issue by Arkoth79** [brainfoolong/web-ftp-client#5]
Hello,

First, excuse me for my english, I'm french, I will do my best ;)

I would like to try this software on my Synology DS214SE (DSM 6.1.3-15152 Update 5 2017/09/21)
Software release-0.12.0.zip (Alpha 4)

So, I've done this :

> Install the package node.js 4 via synology package manager

![image](https://user-images.githubusercontent.com/24947597/31057067-c5e7c0fc-a6dc-11e7-8cc8-afefcbe9e2b3.png)

It's ok for node.js v4... I think... it's "running".

> Via SSH terminal do the same as install linux. You can for sure use a shared folder.

As linux:

> Download a realase zip and unpack to a directory and switch to that directory
> Run npm install --production

![image](https://user-images.githubusercontent.com/24947597/31057112-79c2d242-a6dd-11e7-93b7-7f4afe35f2df.png)

I can't upload npm-debug.log to this issue direcly, so I upload it to pastebin:
[https://pastebin.com/E9270R6M](https://pastebin.com/E9270R6M)

**I can't find where is my mistake, can you help me please ?**
Thank you.

Best regards

**Comment by brainfoolong** [comment]
Hi, have you tried installing it with `sudo npm install --production` The problems seems that it does not find a home directory for your current ssh user.

**Comment by Arkoth79** [comment]
Hello brainfoolong,

Thank you ! it works with `sudo` command => install ok
now launching the daemon server:

> ./wfc start

I can access the gui with the `ip_nas:4340` in firefox for example
It's Ok !!! Thank you !!! ;)


But now, an other problem...
I want to access to a SFTP server which is on an other synology: 
That works with filezilla on windows: first time I'm connecting I must accept a key, then I can see the folders/files from the server, and I can download/upload, no problem.

But with the web-ftp-client, I don't understand, with same settings to connect to the server, I have error:
![image](https://user-images.githubusercontent.com/24947597/31095768-42def818-a7ba-11e7-9b7e-bd7b4440aaff.png)
It don't ask me to accept the key... and it give me a red error message as you can see.

**Any idea for this problem ? maybe you prefer I post an other issue and close this one ?**

Best regards

**Comment by brainfoolong** [comment]
This is probably because your used SFTP is not compatible with this web ftp client. Supported cipher's are 

	aes128-ctr
	aes192-ctr
	aes256-ctr
	aes128-gcm (node v0.11.12 or newer)
	aes128-gcm@openssh.com (node v0.11.12 or newer)
	aes256-gcm (node v0.11.12 or newer)
	aes256-gcm@openssh.com (node v0.11.12 or newer)
	aes256-cbc
	aes192-cbc
	aes128-cbc
	blowfish-cbc
	3des-cbc
	arcfour256
	arcfour128
	cast128-cbc
	arcfour

**Comment by brainfoolong** [comment]
I close this.
