### ISSUE TITLE
Web FTP Client could not start

### ISSUE THREAD

**Issue by jones1008** [brainfoolong/web-ftp-client#8]
I tried to install the latest alpha 4 on my debian system this way:
```
apt-get install nodejs
apt-get install npm
cd /var/www/sftp-client
wget https://github.com/[...]/release-0.12.0.zip
unzip release-0.11.0.zip
npm install --production
chmod 755 wfc
./wfc start
```

the last command gives me the error:
> Starting Web FTP Client... Web FTP Client could not start

the ./logs/error.log file says:
> ./wfc: 42: ./wfc: node: not found

What am I doing wrong?

note: I am very new to node.js

**Comment by brainfoolong** [comment]
Check if `nodejs -v` give you some output.
If yes, this will help you

    sudo ln -s `which nodejs` /usr/bin/node    

Than you have an alias for `nodejs` to `node`.

**Comment by jones1008** [comment]
thanks!
This helped!

**Comment by brainfoolong** [comment]
great
