### ISSUE TITLE
Local folder now working

### ISSUE THREAD

**Issue by alanmilinovic** [brainfoolong/web-ftp-client#9]
Hi,

first of all, great peace of work. Unfortunately I cannot see local folder, it is empty.

I've installed npm and node on my Raspberry and followed instructions on your page. Created connection on localhost (what is raspberry) and tried to create folder and delete some folders and files, and that is working fine.

But I have no option to download files, because my right side is empty so I don't see my local files on my windows 10 machine. I also tried to enter "c:\" but nothing happen. What could be a problem?

Thank you in advance.

**Comment by brainfoolong** [comment]
The right side is the server, the left side is local.

So when right is empty, it seems you've not created a successfull connection to a server. You should see the errors in the top log area.

**Comment by alanmilinovic** [comment]
In my case left side is server and right side is local which is empty. I see this error message: connect ECONNREFUSED localhost:21

**Comment by brainfoolong** [comment]
Ok, let's call it "left side is local", right side is "remote".

And the error says all "ECONNREFUSED". You cannot establish a connection to localhost, maybe because there is no valid FTP/SFTP running or installed on that port.

And, localhost is always the machine that running web-ftp client. So left and right is always the same in your case. I guess you've mixed some things up.

**Comment by alanmilinovic** [comment]
Now I used hostname and receive: Timed out while waiting for handshake. How is it possible?

My SFTP connection is working fine I test it from windows machine and also from my Android device.

**Comment by brainfoolong** [comment]
I don't know what you try here?

What do you want in the left window (it's obviously a local file browser) and what do you want in the right window (It's the remote machine you are connecting to)

**Comment by alanmilinovic** [comment]
Ok, I think I know what could be the problem. I installed this on my Raspberry and I made connection on same machine in Servermanager tab. So basically my remote side is the same machine where web-ftp-client is installed.

**Comment by brainfoolong** [comment]
Yes, as i've said previously, i guess you have mixed some things up.

**Comment by alanmilinovic** [comment]
Then I need web-ftp-server for my raspberry. :)

But not sure if it is possible to display local files on the web where url is opened, it is probably security issue.

**Comment by brainfoolong** [comment]
Ok i close this issue because it's not an issue for this project.
